import "@styles/globals.css";

export const metadata = {
  title: "OChexagon | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container w-full min-h-screen">{children}</div>
      </body>
    </html>
  );
}
